"""Generate src/unicode_tbl.h: codepoint ranges for Unicode general
categories L (letter), M (mark) and N (number).

The tokenizer pre-split regex used by Qwen3.5 refers to \\p{L}, \\p{M} and
\\p{N}.  ANSI C has no Unicode property database, so we bake the ranges into
a static table at build time.  Run this only when regenerating the header:

    python3 tools/gen_unicode.py

The generated header is checked in, so building infer never requires Python.
"""

import unicodedata

MAX = 0x110000
groups = {'L': set(), 'M': set(), 'N': set()}
for cp in range(MAX):
    c = unicodedata.category(chr(cp))[0]
    if c in groups:
        groups[c].add(cp)


def ranges(s):
    out = []
    st = prev = None
    for cp in sorted(s):
        if st is None:
            st = prev = cp
            continue
        if cp == prev + 1:
            prev = cp
            continue
        out.append((st, prev))
        st = prev = cp
    if st is not None:
        out.append((st, prev))
    return out


L = ["/* Generated by tools/gen_unicode.py -- do not edit. */",
     "#ifndef INFER_UNICODE_TBL_H",
     "#define INFER_UNICODE_TBL_H",
     ""]
for g in ('L', 'M', 'N'):
    r = ranges(groups[g])
    L.append("#define UC_%s_COUNT %d" % (g, len(r)))
    L.append("static const unsigned long uc_%s_tbl[UC_%s_COUNT][2] = {" % (g.lower(), g))
    for i in range(0, len(r), 6):
        L.append("  " + " ".join("{0x%X,0x%X}," % (a, b) for a, b in r[i:i + 6]))
    L.append("};")
    L.append("")
L.append("#endif")

open('src/unicode_tbl.h', 'w').write("\n".join(L) + "\n")
print("wrote src/unicode_tbl.h")
